apiVersion: v1
kind: ConfigMap
metadata:
  name: nestjs-auto-config
  namespace: nestjs-auto
data:
  NODE_ENV: production
  PORT: "3000"
  PAYMENTS_URL: https://httpbun.com
  PAYMENTS_MOCK_5XX_RATE: "0.02"
