apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-auto
  namespace: nestjs-auto
  labels:
    app.kubernetes.io/name: nestjs-auto
    app.kubernetes.io/part-of: datadog-instrumentation-lab
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: nestjs-auto
    tags.datadoghq.com/version: "0.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nestjs-auto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nestjs-auto
        app.kubernetes.io/part-of: datadog-instrumentation-lab
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: nestjs-auto
        tags.datadoghq.com/version: "0.0.1"
      annotations:
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/js-lib.version: latest
    spec:
      containers:
        - name: app
          image: localhost:5001/nestjs-dd-base:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: PAYMENTS_URL
              value: https://httpbun.com
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
