apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: gab-coelho-lab
    logLevel: WARN
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    tags:
      - "env:dev"
      - "repo:gab-coelho/nestjs-datadog-instrumentation"
  features:
    apm:
      instrumentation:
        enabled: true
        enabledNamespaces:
          - nestjs-auto
        libVersions:
          js: latest
