apiVersion: v1
kind: Service
metadata:
  name: nestjs-manual
  namespace: nestjs-manual
  labels:
    app.kubernetes.io/name: nestjs-manual
    app.kubernetes.io/part-of: datadog-instrumentation-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nestjs-manual
  ports:
    - name: http
      port: 3000
      targetPort: http
